package com.dj.greendao.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.bw.erzhoumoni.bean.ResultBean;
import com.bw.erzhoumoni.bean.ShoppingCartListBean;

import com.dj.greendao.dao.ResultBeanDao;
import com.dj.greendao.dao.ShoppingCartListBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig resultBeanDaoConfig;
    private final DaoConfig shoppingCartListBeanDaoConfig;

    private final ResultBeanDao resultBeanDao;
    private final ShoppingCartListBeanDao shoppingCartListBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        resultBeanDaoConfig = daoConfigMap.get(ResultBeanDao.class).clone();
        resultBeanDaoConfig.initIdentityScope(type);

        shoppingCartListBeanDaoConfig = daoConfigMap.get(ShoppingCartListBeanDao.class).clone();
        shoppingCartListBeanDaoConfig.initIdentityScope(type);

        resultBeanDao = new ResultBeanDao(resultBeanDaoConfig, this);
        shoppingCartListBeanDao = new ShoppingCartListBeanDao(shoppingCartListBeanDaoConfig, this);

        registerDao(ResultBean.class, resultBeanDao);
        registerDao(ShoppingCartListBean.class, shoppingCartListBeanDao);
    }
    
    public void clear() {
        resultBeanDaoConfig.clearIdentityScope();
        shoppingCartListBeanDaoConfig.clearIdentityScope();
    }

    public ResultBeanDao getResultBeanDao() {
        return resultBeanDao;
    }

    public ShoppingCartListBeanDao getShoppingCartListBeanDao() {
        return shoppingCartListBeanDao;
    }

}
